### ISSUE TITLE
ModelAdminGroup with only one item error

### ISSUE THREAD

**Issue by jordij** [ababic/wagtailmodeladmin#27]
I know it might seem a stupid case but... I get this error if I try to create a group with only one item in `items` field:

```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 228, in patch_all
    patch_root_urlconf()
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 216, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 549, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 351, in app_dict
    self._populate()
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 284, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/nzredcross/nzredcross/urls.py", line 9, in <module>
    from wagtail.wagtailadmin import urls as wagtailadmin_urls
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/wagtail/wagtailadmin/urls/__init__.py", line 42, in <module>
    for fn in hooks.get_hooks('register_admin_urls'):
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/wagtail/wagtailcore/hooks.py", line 44, in get_hooks
    search_for_hooks()
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/wagtail/wagtailcore/hooks.py", line 39, in search_for_hooks
    list(get_app_submodules('wagtail_hooks'))
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/wagtail/utils/apps.py", line 23, in get_app_submodules
    yield name, import_module('%s.%s' % (name, submodule_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/nzredcross/volunteer/wagtail_hooks.py", line 24, in <module>
    wagtailmodeladmin_register(VolunteerAdminGroup)
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/wagtailmodeladmin/options.py", line 504, in wagtailmodeladmin_register
    instance = wagtailmodeladmin_class()
  File "/home/vagrant/.virtualenvs/nzredcross/local/lib/python2.7/site-packages/wagtailmodeladmin/options.py", line 405, in __init__
    for ModelAdminClass in self.items:
TypeError: 'type' object is not iterable
```

More than one works just fine.

**Comment by ababic** [comment]
Hi @jordij. So, it's quite possible to have a group with just one item (although, just registering your single ModelAdmin class would be make accessing the list page easier). You still have to provide an iterable for 'items' though,  even if there's just one item in it. If a tuple, check your syntax... You probably need a comma in there before the closing bracket.

**Comment by jordij** [comment]
Thanks @ababic, you're right indeed. Sorry!
